### ISSUE TITLE
Rename  hySpc.pkgs and  hySpc.skeleton and leave "hySpc" pattern for packages only

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.pkgs#10]
I suggest leaving `hySpc` pattern for packages only and renaming the other non-package repositories.

Maybe it is reasonable to rename ` hySpc.pkgs` into `packages` or `download`, or `server`, or `resources`?
Then the URL would be, e.g., https://r-hyperspec.github.io/packages/

**Comment by GegznaV** [comment]
I also think that this repo (currently `r-hyperspec/hySpc.pkgs`) could be used to update the files that are common for all packages (e.g., GH actions workflow files): we can create an action that downloads these files if they are updated in `r-hyperspec/hySpc.pkgs`. (Of cource, we can use a separate repo for this purpose).

I write this message here as it may have an influence on the decision of the new name of the repo.

**Comment by GegznaV** [comment]
On slack, we (Bryan and I) agreed to rename `hySpc.pkgs`. The name `packages` is a good candidate but there is a question:

>I wonder if  `packages` might conflict with some Github actions or other reserved words. 

This should be investigated.

**Comment by bryanhanson** [comment]
This was resolved some time ago.
