### ISSUE TITLE
Formating of directory listing

### ISSUE THREAD

**Issue by bryanhanson** [r-hyperspec/hySpc.pkgs#16]
In `drat--update-readme.yaml` (by the way, could the -- in the name become a single - ?) this line:

```
awk '{print "- **"$2"**", $3, "_("$1")_"}'|\
```
along with the other code produces lines like this:

> **hyperSpec** 0.100.0 _(2020-08-20)_

which to my eye is visually a bit hard to process.  I would suggest either don't use parentheses or don't italicize the date string.  VG also mentioned that he might turn it into a table which would probably be visually better as well.

**Comment by GegznaV** [comment]
What's about this version: 
![image](https://user-images.githubusercontent.com/12725868/90808481-be5a3000-e328-11ea-876b-b0b94c14bd98.png)

**Comment by bryanhanson** [comment]
That's nice!

**Comment by GegznaV** [comment]
And here how it looks in the form of a table:

![image](https://user-images.githubusercontent.com/12725868/90823607-d472eb00-e33e-11ea-9029-a0c79a10d389.png)

***

So which one should be used?

**Comment by bryanhanson** [comment]
The table is awesome, use it!

**Comment by GegznaV** [comment]
If table is OK, then I'm closing this issue.
