### ISSUE TITLE
SKELETON must not be listed in the list of packages to download

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.pkgs#21]
In https://r-hyperspec.github.io/pkg-repo/, `SKELETON` must not be listed in the list of packages to download:

![image](https://user-images.githubusercontent.com/12725868/125682677-d16eebd4-cda7-481d-83cd-bc50c6709c1b.png)

**Comment by bryanhanson** [comment]
That needs to be manually removed. It came from one of the other packages that had not had the `SKELETON` renamed.  Let me know if you want me to fix (manually modifications are described in `README.md` or a similar file).

**Comment by GegznaV** [comment]
Yes, please remove `SKELETON` and the archived version of `hyperSpec` (the second table below this one).

**Comment by bryanhanson** [comment]
Fixed via https://github.com/r-hyperspec/pkg-repo/commit/d110920202402183d68eccfbc1be831f6b639444 I may have misunderstood and removed all versions of `hyperSpec` but the next push on that package will be deployed.

**Comment by GegznaV** [comment]
Thanks
