### ISSUE TITLE
Remove branch gh-pages and deploy from master

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.pkgs#3]
Why do we use two identical branches (`master` and `gh-pages`) when only one is sufficient? 

![image](https://user-images.githubusercontent.com/12725868/90312485-83619200-df0d-11ea-83cc-8975c0d6cb1e.png)

Why can't we delete `gh-pages` and deploy Git Pages from `master`. It would allow simplifying **drat** related code a bit and will remove some confusion.

**Comment by bryanhanson** [comment]
I suppose we could.  I'll look into it.  I have some other simplifications in mind too.

**Comment by GegznaV** [comment]
I was experimenting with **drat**-related code that modifies README. I wrote analogous code in R, used several packages that were updated on several different days. Unfortunately, in the README all the dates were the same: it was the date of the day when the code was run. Does this aspect was tested in the `awk` related output and was it confirmed that this issue is not present?

**Comment by bryanhanson** [comment]
Not sure I understand your last sentence completely.  The current code builds and checks the package and then deploys it, so the date is always the date the build and check was done (for instance, in `hySpec.read.txt`).  This is because what you see in `README.md` comes from an `ls` command which retrieves the modification date of the file.

**Comment by GegznaV** [comment]
I mixed 2 separate issues here, so I move the second one (related to dates) to #4.

**Comment by bryanhanson** [comment]
It has to be the other way around, as `drat` requires using the `gh-pages` branch.  So I have made some appropriate changes.  I made `gh-pages` the default branch.  And I think eventually we can delete the master branch, but not until we have fixed everything else.

**Comment by GegznaV** [comment]
> It has to be the other way around, as `drat` requires using the `gh-pages`

No, the branch does not have to be `gh-pages`. With proper setup, it is totally OK to have a single branch `master`. I tried it and it works as expected. 

I do not have admin right so I cannot check if the setup is proper. I think it is more usual to delete `gh-pages` and use `master` only.

**Comment by bryanhanson** [comment]
i guess I was not clear. A single branch is fine, but it must be `gh-pages`.  This is a requirement of `drat` as I read the documentation.

**Comment by GegznaV** [comment]
Yes, I read all the vignettes. Most of them are written in 2015 and a lot of things have changed in GitHub. Some updates were made within last month. It is accented a lot that the `gh-pages` branch should be used. But the essence is that the Git Pages should be published as a website but it *does not matter* what the source of the website is: `gh-pages`, `master`, or any other branch that can be used as a source. Now even a sub-directory of `gh-pages` or `master` could be used the source. And I tried that: `master` only is sufficient.

Yet, it is not a big thing. If it takes less effort to use `gh-pages`, so let's do it! 

Just the same setup should be used across all repos. And it would be nice if it would be described somewhere how do the **drat**-related system works in `r-hyperspec`. Maybe the comment in GitHub Actions workflow are also OK for this purpose.

**Comment by bryanhanson** [comment]
Thanks for the clarification and update.  The only place this matters is `hySpc.pkgs` so let's just stick with `gh-pages` for now.  There will never be a vignette that would need that branch.

`CONTRIBUTING.md` has some information on how the `drat` system works but after the latest set of changes it needs to be updated (issue #8).

**Comment by bryanhanson** [comment]
I removed the `master` branch, and did a test push from `hySpc.read.txt`; everything seems functional so we are operating only on `gh-pages`.  Closing.
