### ISSUE TITLE
Investigate the dates reported for the packages on README.md

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.pkgs#4]
It should be tested if package updates from several repositories work as expected. Especially, the attention should be paid to the dates in the README file when different packages are updated on different dates. Do the dates of packages updated earlier get overwritten?

I ran some preliminary tests and they showed that when the code is run locally, the dates are correct, but when they run on GitHub Actions, the dates are set to the same date when the code was run the last time (It might be that the date attribute is lost and overwritten during `git clone`).

Originally this issue was raised in https://github.com/r-hyperspec/hySpc.pkgs/issues/3#issuecomment-674394270 as:

> I was experimenting with **drat**-related code that modifies README. I wrote analogous code in R, used several packages that were updated on several different days. Unfortunately, in the README all the dates were the same: it was the date of the day when the code was run. Does this aspect was tested in the `awk` related output and was it confirmed that this issue is not present?

**Comment by GegznaV** [comment]
![image](https://user-images.githubusercontent.com/12725868/90338627-9c447300-dff3-11ea-96d8-f2ffc4bb06b7.png)

This is what I was talking about: the packages are built on different days (see print-screen below), but in README the date is the same (print-screen above).

![image](https://user-images.githubusercontent.com/12725868/90338684-078e4500-dff4-11ea-808b-62ef516494fa.png)

**Comment by bryanhanson** [comment]
I'll look into this after a few other tasks are complete.  One thing we could do is not display the date at all, but I would rather have the correct date displayed.

**Comment by bryanhanson** [comment]
We decided to not display the dates!
