### ISSUE TITLE
Should the archived versions of the same package be listed in README?

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.pkgs#5]
When the package version is updated, the old version is moved to the `Archive` folder.  Should several versions of the same package (including those in the `Archive` folder) be listed in the README file? Or would it be enough to show the newest version only?

***

Currently, all files are listed:

```bash
ls -lhR  --time-style=long-iso | grep \.tar\.gz$ | awk '{print "\n* "$8, " ("$6")"}' >> README.tmp
```

And this code would exclude the files in the `Archive`:
```bash
ls -lhR  --time-style=long-iso --ignore='Archive' | grep \.tar\.gz$ | awk '{print "\n* "$8, " ("$6")"}' >> README.tmp
```

**Comment by bryanhanson** [comment]
I think it would be kinder to the user to show them all available packages.

**Comment by GegznaV** [comment]
I also think that all available versions should be listed. But I'm not sure what is the optimal form to do that. Still, maybe now it's too early to decide on this as there is only a single package included in the **dart** repo.

**Comment by bryanhanson** [comment]
Closing for now, there are more pressing issues and limited time.
