### ISSUE TITLE
Is organization-level access token needed?

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.pkgs#9]
GitHub organizations can have access tokens (via secrets) that are common for all repos. I think this kind of token could be helpful for **drat** strategy as we would not have to set separate tokens for each repository.

Should we have a token like this, or should we set separate tokens for each repo, or token are not needed at all within the same organization?

**Comment by bryanhanson** [comment]
One definitely needs the token.  And yes, we should try to use the same token across all repos for convenience.

**Comment by GegznaV** [comment]
Is this issue already solved?

**Comment by cbeleites** [comment]
@GegznaV please document the solution :-)

**Comment by GegznaV** [comment]
This is the extended message from Slack conversation:
***
The steps I took to make authentication work:

1. In my personal settings:
    - created a PAT with the scopes I described above (repo and email)
    - copied the value of the PAT.
2.  In the organization on interest:
    - I created an organization-level secret with the name `DEPLOY_TOKEN`. The value was the PAT I created before.
    - I enabled the secret to be accessible by certain repos only.
3. In the workflow file of a certain repo:
    - I used the secret as an environment variable.

***

**Comment by bryanhanson** [comment]
Fixed.
